kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc2
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqlrs4
spec:
  replicas: 1
  selector:
    matchExpressions:

    - {key: env,operator: In,values: [dev]}
  template:
    metadata:
      name: mysqlpod2
      labels:
        env: dev
    spec:
      containers:
      - name: "mysql"
        image: "mysql:5.6"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
               name: mysqlsecret
               key: rootpassword

        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
               name: mysqlsecret
               key: dbname
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
               name: mysqlsecret
               key: user

        - name: MYSQL_PASSWORD
          valueFrom:
           secretKeyRef:
               name: mysqlsecret
               key: password

        volumeMounts:
        - mountPath: /var/lib/mysql
          name: task-pv-storage1
      volumes:
      - name: task-pv-storage1
        persistentVolumeClaim:
           claimName: pvc2
---
apiVersion: v1
kind: Service
metadata:
  name: sqllb
spec:
  clusterIP: None
  selector:
    env: dev
  type: "ClusterIP"
  ports:
    - port: 8500
      targetPort: 3306
