kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycloud
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: pod1
      labels:
        tier: frontend
    spec:      
      containers:
      - name: "cc1"
        image: "nextcloud:latest"
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: sqllb
        - name: MYSQL_USER
          valueFrom:
               secretKeyRef:
                 name: mysqlsecret
                 key: wpuser
        - name: MYSQL_PASSWORD
          valueFrom:
               secretKeyRef:
                 name: mysqlsecret
                 key: wppass
        - name: MYSQL_DATABASE
          valueFrom:
               secretKeyRef:
                 name: mysqlsecret
                 key: wpname
        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud-storage
      volumes:
      - name: nextcloud-storage
        persistentVolumeClaim:
           claimName: pvc1
---
apiVersion: v1
kind: Service
metadata:
  name: cloudnext-lb
spec:
  selector:
    tier: frontend
  ports:
    - port: 8000
      targetPort: 80
  type: LoadBalancer


